before_deploy: move /y src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec.backup src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec | nuget pack src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec
deploy:
  provider: NuGet
  api_key: 
    secure: XclGUFnDjfd9zzPCUifE4TZlxMEhUtbI5d15A1Fd7GJi/lmCKnad+ZVsWYcm/njS
  artifact: TBA*.nupkg
