before_deploy: del src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec | rename src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec.backup com.tweirtx.TBAAPIv3client.nuspec | nuget pack src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec
deploy:
  provider: NuGet
  api_key: 
    secure: XclGUFnDjfd9zzPCUifE4TZlxMEhUtbI5d15A1Fd7GJi/lmCKnad+ZVsWYcm/njS
  artifact: TBAAPIv3client.*.nupkg
