before_deploy: move /y src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec.backup src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec | nuget pack src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec | appveyor PushArtifact '/.*\.nupkg/'
deploy:
  provider: NuGet
  artifacts: 
    - path: /.*\.nupkg/
  api_key:
    secure: 7rvP7Js1KhYJYbmLljz7NLskbNJFpBdsJIzeMsfvLAzF0zZp14led4speLiLFsGK
after_deploy: dir
