before_deploy: move /y src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec.backup src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec | nuget pack src\com.tweirtx.TBAAPIv3client\com.tweirtx.TBAAPIv3client.nuspec
deploy:
  provider: NuGet
  api_key: 
    artifact: TBAAPIv3client.3.4.1.nupkg
after_deploy: dir
