/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing TeamEventStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamEventStatusTests
    {
        // TODO uncomment below to declare an instance variable for TeamEventStatus
        //private TeamEventStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamEventStatus
            //instance = new TeamEventStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamEventStatus
        /// </summary>
        [Test]
        public void TeamEventStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventStatus
            //Assert.IsInstanceOfType<TeamEventStatus> (instance, "variable 'instance' is a TeamEventStatus");
        }


        /// <summary>
        /// Test the property 'Qual'
        /// </summary>
        [Test]
        public void QualTest()
        {
            // TODO unit test for the property 'Qual'
        }
        /// <summary>
        /// Test the property 'Alliance'
        /// </summary>
        [Test]
        public void AllianceTest()
        {
            // TODO unit test for the property 'Alliance'
        }
        /// <summary>
        /// Test the property 'Playoff'
        /// </summary>
        [Test]
        public void PlayoffTest()
        {
            // TODO unit test for the property 'Playoff'
        }
        /// <summary>
        /// Test the property 'AllianceStatusStr'
        /// </summary>
        [Test]
        public void AllianceStatusStrTest()
        {
            // TODO unit test for the property 'AllianceStatusStr'
        }
        /// <summary>
        /// Test the property 'PlayoffStatusStr'
        /// </summary>
        [Test]
        public void PlayoffStatusStrTest()
        {
            // TODO unit test for the property 'PlayoffStatusStr'
        }
        /// <summary>
        /// Test the property 'OverallStatusStr'
        /// </summary>
        [Test]
        public void OverallStatusStrTest()
        {
            // TODO unit test for the property 'OverallStatusStr'
        }
        /// <summary>
        /// Test the property 'NextMatchKey'
        /// </summary>
        [Test]
        public void NextMatchKeyTest()
        {
            // TODO unit test for the property 'NextMatchKey'
        }
        /// <summary>
        /// Test the property 'LastMatchKey'
        /// </summary>
        [Test]
        public void LastMatchKeyTest()
        {
            // TODO unit test for the property 'LastMatchKey'
        }

    }

}
