/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.tweirtx.tba-api-v3-client.Api;
using com.tweirtx.tba-api-v3-client.Model;
using com.tweirtx.tba-api-v3-client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.tweirtx.tba-api-v3-client.Test
{
    /// <summary>
    ///  Class for testing MatchSimple
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MatchSimpleTests
    {
        // TODO uncomment below to declare an instance variable for MatchSimple
        //private MatchSimple instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatchSimple
            //instance = new MatchSimple();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatchSimple
        /// </summary>
        [Test]
        public void MatchSimpleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MatchSimple
            //Assert.IsInstanceOfType<MatchSimple> (instance, "variable 'instance' is a MatchSimple");
        }


        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Test]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }
        /// <summary>
        /// Test the property 'CompLevel'
        /// </summary>
        [Test]
        public void CompLevelTest()
        {
            // TODO unit test for the property 'CompLevel'
        }
        /// <summary>
        /// Test the property 'SetNumber'
        /// </summary>
        [Test]
        public void SetNumberTest()
        {
            // TODO unit test for the property 'SetNumber'
        }
        /// <summary>
        /// Test the property 'MatchNumber'
        /// </summary>
        [Test]
        public void MatchNumberTest()
        {
            // TODO unit test for the property 'MatchNumber'
        }
        /// <summary>
        /// Test the property 'Alliances'
        /// </summary>
        [Test]
        public void AlliancesTest()
        {
            // TODO unit test for the property 'Alliances'
        }
        /// <summary>
        /// Test the property 'WinningAlliance'
        /// </summary>
        [Test]
        public void WinningAllianceTest()
        {
            // TODO unit test for the property 'WinningAlliance'
        }
        /// <summary>
        /// Test the property 'EventKey'
        /// </summary>
        [Test]
        public void EventKeyTest()
        {
            // TODO unit test for the property 'EventKey'
        }
        /// <summary>
        /// Test the property 'Time'
        /// </summary>
        [Test]
        public void TimeTest()
        {
            // TODO unit test for the property 'Time'
        }
        /// <summary>
        /// Test the property 'PredictedTime'
        /// </summary>
        [Test]
        public void PredictedTimeTest()
        {
            // TODO unit test for the property 'PredictedTime'
        }
        /// <summary>
        /// Test the property 'ActualTime'
        /// </summary>
        [Test]
        public void ActualTimeTest()
        {
            // TODO unit test for the property 'ActualTime'
        }

    }

}
