/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using net.thefletcher.tbaapi.v3client.Api;
using net.thefletcher.tbaapi.v3client.Model;
using net.thefletcher.tbaapi.v3client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace net.thefletcher.tbaapi.v3client.Test
{
    /// <summary>
    ///  Class for testing EventRankingRankings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EventRankingRankingsTests
    {
        // TODO uncomment below to declare an instance variable for EventRankingRankings
        //private EventRankingRankings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventRankingRankings
            //instance = new EventRankingRankings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventRankingRankings
        /// </summary>
        [Test]
        public void EventRankingRankingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EventRankingRankings
            //Assert.IsInstanceOf(typeof(EventRankingRankings), instance);
        }


        /// <summary>
        /// Test the property 'MatchesPlayed'
        /// </summary>
        [Test]
        public void MatchesPlayedTest()
        {
            // TODO unit test for the property 'MatchesPlayed'
        }
        /// <summary>
        /// Test the property 'QualAverage'
        /// </summary>
        [Test]
        public void QualAverageTest()
        {
            // TODO unit test for the property 'QualAverage'
        }
        /// <summary>
        /// Test the property 'ExtraStats'
        /// </summary>
        [Test]
        public void ExtraStatsTest()
        {
            // TODO unit test for the property 'ExtraStats'
        }
        /// <summary>
        /// Test the property 'SortOrders'
        /// </summary>
        [Test]
        public void SortOrdersTest()
        {
            // TODO unit test for the property 'SortOrders'
        }
        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Test]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Dq'
        /// </summary>
        [Test]
        public void DqTest()
        {
            // TODO unit test for the property 'Dq'
        }
        /// <summary>
        /// Test the property 'TeamKey'
        /// </summary>
        [Test]
        public void TeamKeyTest()
        {
            // TODO unit test for the property 'TeamKey'
        }

    }

}
