/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.tweirtx.TBAAPIv3client.Api;
using com.tweirtx.TBAAPIv3client.Model;
using com.tweirtx.TBAAPIv3client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.tweirtx.TBAAPIv3client.Test
{
    /// <summary>
    ///  Class for testing DistrictRankingEventPoints
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DistrictRankingEventPointsTests
    {
        // TODO uncomment below to declare an instance variable for DistrictRankingEventPoints
        //private DistrictRankingEventPoints instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DistrictRankingEventPoints
            //instance = new DistrictRankingEventPoints();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DistrictRankingEventPoints
        /// </summary>
        [Test]
        public void DistrictRankingEventPointsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DistrictRankingEventPoints
            //Assert.IsInstanceOfType<DistrictRankingEventPoints> (instance, "variable 'instance' is a DistrictRankingEventPoints");
        }


        /// <summary>
        /// Test the property 'EventKey'
        /// </summary>
        [Test]
        public void EventKeyTest()
        {
            // TODO unit test for the property 'EventKey'
        }
        /// <summary>
        /// Test the property 'DistrictCmp'
        /// </summary>
        [Test]
        public void DistrictCmpTest()
        {
            // TODO unit test for the property 'DistrictCmp'
        }
        /// <summary>
        /// Test the property 'AlliancePoints'
        /// </summary>
        [Test]
        public void AlliancePointsTest()
        {
            // TODO unit test for the property 'AlliancePoints'
        }
        /// <summary>
        /// Test the property 'AwardPoints'
        /// </summary>
        [Test]
        public void AwardPointsTest()
        {
            // TODO unit test for the property 'AwardPoints'
        }
        /// <summary>
        /// Test the property 'QualPoints'
        /// </summary>
        [Test]
        public void QualPointsTest()
        {
            // TODO unit test for the property 'QualPoints'
        }
        /// <summary>
        /// Test the property 'ElimPoints'
        /// </summary>
        [Test]
        public void ElimPointsTest()
        {
            // TODO unit test for the property 'ElimPoints'
        }
        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Test]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

    }

}
