/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.tweirtx.TBAAPIv3client.Api;
using com.tweirtx.TBAAPIv3client.Model;
using com.tweirtx.TBAAPIv3client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.tweirtx.TBAAPIv3client.Test
{
    /// <summary>
    ///  Class for testing EliminationAllianceStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EliminationAllianceStatusTests
    {
        // TODO uncomment below to declare an instance variable for EliminationAllianceStatus
        //private EliminationAllianceStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EliminationAllianceStatus
            //instance = new EliminationAllianceStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EliminationAllianceStatus
        /// </summary>
        [Test]
        public void EliminationAllianceStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EliminationAllianceStatus
            //Assert.IsInstanceOfType<EliminationAllianceStatus> (instance, "variable 'instance' is a EliminationAllianceStatus");
        }


        /// <summary>
        /// Test the property 'CurrentLevelRecord'
        /// </summary>
        [Test]
        public void CurrentLevelRecordTest()
        {
            // TODO unit test for the property 'CurrentLevelRecord'
        }
        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Test]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }
        /// <summary>
        /// Test the property 'PlayoffAverage'
        /// </summary>
        [Test]
        public void PlayoffAverageTest()
        {
            // TODO unit test for the property 'PlayoffAverage'
        }
        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Test]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
