/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * OpenAPI spec version: 3.03.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.tweirtx.TBAAPIv3client.Api;
using com.tweirtx.TBAAPIv3client.Model;
using com.tweirtx.TBAAPIv3client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.tweirtx.TBAAPIv3client.Test
{
    /// <summary>
    ///  Class for testing TeamEventStatusRankRanking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class TeamEventStatusRankRankingTests
    {
        // TODO uncomment below to declare an instance variable for TeamEventStatusRankRanking
        //private TeamEventStatusRankRanking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TeamEventStatusRankRanking
            //instance = new TeamEventStatusRankRanking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TeamEventStatusRankRanking
        /// </summary>
        [Test]
        public void TeamEventStatusRankRankingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" TeamEventStatusRankRanking
            //Assert.IsInstanceOfType<TeamEventStatusRankRanking> (instance, "variable 'instance' is a TeamEventStatusRankRanking");
        }


        /// <summary>
        /// Test the property 'Dq'
        /// </summary>
        [Test]
        public void DqTest()
        {
            // TODO unit test for the property 'Dq'
        }
        /// <summary>
        /// Test the property 'MatchesPlayed'
        /// </summary>
        [Test]
        public void MatchesPlayedTest()
        {
            // TODO unit test for the property 'MatchesPlayed'
        }
        /// <summary>
        /// Test the property 'QualAverage'
        /// </summary>
        [Test]
        public void QualAverageTest()
        {
            // TODO unit test for the property 'QualAverage'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Test]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Record'
        /// </summary>
        [Test]
        public void RecordTest()
        {
            // TODO unit test for the property 'Record'
        }
        /// <summary>
        /// Test the property 'SortOrders'
        /// </summary>
        [Test]
        public void SortOrdersTest()
        {
            // TODO unit test for the property 'SortOrders'
        }
        /// <summary>
        /// Test the property 'TeamKey'
        /// </summary>
        [Test]
        public void TeamKeyTest()
        {
            // TODO unit test for the property 'TeamKey'
        }

    }

}
