/* 
 * The Blue Alliance API v3
 *
 * # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
 *
 * The version of the OpenAPI document: 3.8.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using com.thebluealliance.TBAAPI.v3client.Api;
using com.thebluealliance.TBAAPI.v3client.Model;
using com.thebluealliance.TBAAPI.v3client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace com.thebluealliance.TBAAPI.v3client.Test
{
    /// <summary>
    ///  Class for testing MatchTimeseries2018
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MatchTimeseries2018Tests
    {
        // TODO uncomment below to declare an instance variable for MatchTimeseries2018
        //private MatchTimeseries2018 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MatchTimeseries2018
            //instance = new MatchTimeseries2018();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MatchTimeseries2018
        /// </summary>
        [Test]
        public void MatchTimeseries2018InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" MatchTimeseries2018
            //Assert.IsInstanceOf(typeof(MatchTimeseries2018), instance);
        }


        /// <summary>
        /// Test the property 'EventKey'
        /// </summary>
        [Test]
        public void EventKeyTest()
        {
            // TODO unit test for the property 'EventKey'
        }
        /// <summary>
        /// Test the property 'MatchId'
        /// </summary>
        [Test]
        public void MatchIdTest()
        {
            // TODO unit test for the property 'MatchId'
        }
        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Test]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }
        /// <summary>
        /// Test the property 'Play'
        /// </summary>
        [Test]
        public void PlayTest()
        {
            // TODO unit test for the property 'Play'
        }
        /// <summary>
        /// Test the property 'TimeRemaining'
        /// </summary>
        [Test]
        public void TimeRemainingTest()
        {
            // TODO unit test for the property 'TimeRemaining'
        }
        /// <summary>
        /// Test the property 'BlueAutoQuest'
        /// </summary>
        [Test]
        public void BlueAutoQuestTest()
        {
            // TODO unit test for the property 'BlueAutoQuest'
        }
        /// <summary>
        /// Test the property 'BlueBoostCount'
        /// </summary>
        [Test]
        public void BlueBoostCountTest()
        {
            // TODO unit test for the property 'BlueBoostCount'
        }
        /// <summary>
        /// Test the property 'BlueBoostPlayed'
        /// </summary>
        [Test]
        public void BlueBoostPlayedTest()
        {
            // TODO unit test for the property 'BlueBoostPlayed'
        }
        /// <summary>
        /// Test the property 'BlueCurrentPowerup'
        /// </summary>
        [Test]
        public void BlueCurrentPowerupTest()
        {
            // TODO unit test for the property 'BlueCurrentPowerup'
        }
        /// <summary>
        /// Test the property 'BlueFaceTheBoss'
        /// </summary>
        [Test]
        public void BlueFaceTheBossTest()
        {
            // TODO unit test for the property 'BlueFaceTheBoss'
        }
        /// <summary>
        /// Test the property 'BlueForceCount'
        /// </summary>
        [Test]
        public void BlueForceCountTest()
        {
            // TODO unit test for the property 'BlueForceCount'
        }
        /// <summary>
        /// Test the property 'BlueForcePlayed'
        /// </summary>
        [Test]
        public void BlueForcePlayedTest()
        {
            // TODO unit test for the property 'BlueForcePlayed'
        }
        /// <summary>
        /// Test the property 'BlueLevitateCount'
        /// </summary>
        [Test]
        public void BlueLevitateCountTest()
        {
            // TODO unit test for the property 'BlueLevitateCount'
        }
        /// <summary>
        /// Test the property 'BlueLevitatePlayed'
        /// </summary>
        [Test]
        public void BlueLevitatePlayedTest()
        {
            // TODO unit test for the property 'BlueLevitatePlayed'
        }
        /// <summary>
        /// Test the property 'BluePowerupTimeRemaining'
        /// </summary>
        [Test]
        public void BluePowerupTimeRemainingTest()
        {
            // TODO unit test for the property 'BluePowerupTimeRemaining'
        }
        /// <summary>
        /// Test the property 'BlueScaleOwned'
        /// </summary>
        [Test]
        public void BlueScaleOwnedTest()
        {
            // TODO unit test for the property 'BlueScaleOwned'
        }
        /// <summary>
        /// Test the property 'BlueScore'
        /// </summary>
        [Test]
        public void BlueScoreTest()
        {
            // TODO unit test for the property 'BlueScore'
        }
        /// <summary>
        /// Test the property 'BlueSwitchOwned'
        /// </summary>
        [Test]
        public void BlueSwitchOwnedTest()
        {
            // TODO unit test for the property 'BlueSwitchOwned'
        }
        /// <summary>
        /// Test the property 'RedAutoQuest'
        /// </summary>
        [Test]
        public void RedAutoQuestTest()
        {
            // TODO unit test for the property 'RedAutoQuest'
        }
        /// <summary>
        /// Test the property 'RedBoostCount'
        /// </summary>
        [Test]
        public void RedBoostCountTest()
        {
            // TODO unit test for the property 'RedBoostCount'
        }
        /// <summary>
        /// Test the property 'RedBoostPlayed'
        /// </summary>
        [Test]
        public void RedBoostPlayedTest()
        {
            // TODO unit test for the property 'RedBoostPlayed'
        }
        /// <summary>
        /// Test the property 'RedCurrentPowerup'
        /// </summary>
        [Test]
        public void RedCurrentPowerupTest()
        {
            // TODO unit test for the property 'RedCurrentPowerup'
        }
        /// <summary>
        /// Test the property 'RedFaceTheBoss'
        /// </summary>
        [Test]
        public void RedFaceTheBossTest()
        {
            // TODO unit test for the property 'RedFaceTheBoss'
        }
        /// <summary>
        /// Test the property 'RedForceCount'
        /// </summary>
        [Test]
        public void RedForceCountTest()
        {
            // TODO unit test for the property 'RedForceCount'
        }
        /// <summary>
        /// Test the property 'RedForcePlayed'
        /// </summary>
        [Test]
        public void RedForcePlayedTest()
        {
            // TODO unit test for the property 'RedForcePlayed'
        }
        /// <summary>
        /// Test the property 'RedLevitateCount'
        /// </summary>
        [Test]
        public void RedLevitateCountTest()
        {
            // TODO unit test for the property 'RedLevitateCount'
        }
        /// <summary>
        /// Test the property 'RedLevitatePlayed'
        /// </summary>
        [Test]
        public void RedLevitatePlayedTest()
        {
            // TODO unit test for the property 'RedLevitatePlayed'
        }
        /// <summary>
        /// Test the property 'RedPowerupTimeRemaining'
        /// </summary>
        [Test]
        public void RedPowerupTimeRemainingTest()
        {
            // TODO unit test for the property 'RedPowerupTimeRemaining'
        }
        /// <summary>
        /// Test the property 'RedScaleOwned'
        /// </summary>
        [Test]
        public void RedScaleOwnedTest()
        {
            // TODO unit test for the property 'RedScaleOwned'
        }
        /// <summary>
        /// Test the property 'RedScore'
        /// </summary>
        [Test]
        public void RedScoreTest()
        {
            // TODO unit test for the property 'RedScore'
        }
        /// <summary>
        /// Test the property 'RedSwitchOwned'
        /// </summary>
        [Test]
        public void RedSwitchOwnedTest()
        {
            // TODO unit test for the property 'RedSwitchOwned'
        }

    }

}
